version: "1.0"
services:
  mosquitto:
    image: eclipse-mosquitto:2.0.11
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
        - ./mosquitto:/mosquitto/config
    networks:
      - u-network

  axon-u-calculator:
    image: axon-u-calculator:latest
    restart: always
    ports:
      - "5173:80"
    networks:
      - u-network

  axon-u-middle:
    image: axon-u-middle:latest
    restart: always
    ports:
      - "5174:80"
    networks:
      - u-network
  
  axon-u-footer:
    image: axon-u-footer:latest
    restart: always
    ports:
      - "5175:80"
    networks:
      - u-network

  node-red:
    image: nodered/node-red:latest
    restart: always
    ports:
      - "1880:1880"
    volumes:
      - ./node-red/data:/data         # Node-RED persistent data (includes settings & flows)
      # - ./node-red/flows.json:/data/flows.json  # Your initial predefined flow
    networks:
      - u-network  

networks:
  u-network:
    name: u-network
    driver: bridge
  